### ISSUE TITLE
Problem with loading the xml file

### ISSUE THREAD

**Issue by kulmjens** [Sammyboy/MODX-Evolution-Multidomain#1]
Hi there,

I encountered a strange problem with your multidomain solution and the TinyMCE4 plugin on MODX 1.1. In TinyMCE4 there is this dialog when you want to add or edit a link within the content. And in this dialog there is a field called "Search in MODX". So there you can type in anything and you get back a list of documents. Unfortunately it didn't work, because there was an error in the json response from the TinyMCE4 plugin "modxlink" in the file `assets/plugins/tinymce4/tinymce/plugins/modxlink/search.php` which looked like this `ERROR: Failed to open file assets/site/domains.xml!<br />[]` but should be like this: `[]`. This script includes the index.php from the root directory and as I found out the error message came from the file `assets/lib/DocumentParser_Extended.php`.
I don't know why but my solution was to change line 23 from 
```
$xml      = @simplexml_load_file( $this->config['base_path'] . $xml_file, 'SimpleXMLElement', LIBXML_NOCDATA );
```
to
```
$xml      = @simplexml_load_file( MODX_BASE_PATH . $xml_file, 'SimpleXMLElement', LIBXML_NOCDATA );
```
I did some echos and the `$modx->config['base_path']` was empty, whereas the `MODX_BASE_PATH` was set. Strange, because in my site configuration the field "base path" is correctly filled in...

**Comment by Sammyboy** [comment]
Thanks for reporting!
Updated.
